- name: Get oVirt VMs
  ovirt.ovirt.ovirt_vm_info:
    auth:
      url: "{{ ovirt_url }}"
      username: "{{ ovirt_username }}"
      password: "{{ ovirt_password }}"
      ca_file: "{{ ovirt_cafile }}"
  register: ovirt_vms

- name: Get OpenStack networks
  openstack.cloud.network:
    state: present
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project_name }}"
      user_domain_name: "{{ openstack_user_domain_name }}"
      project_domain_name: "{{ openstack_project_domain_name }}"
  register: openstack_networks

- name: Create Neutron ports for oVirt VM NICs
  openstack.cloud.os_port:
    state: present
    name: "{{ vm.name }}-{{ nic.name }}"
    network: "{{ openstack_networks | selectattr('name', 'search', 'vlan' + nic.profile.network.vlan_id | string) | first }}"
    mac_address: "{{ nic.mac.address }}"
    fixed_ips:
      - ip_address: "{{ nic.ip.address }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project_name }}"
      user_domain_name: "{{ openstack_user_domain_name }}"
      project_domain_name: "{{ openstack_project_domain_name }}"
    allowed_address_pairs:
      - ip_address: "{{ nic.ip.address }}"
    device_owner: "compute:None"
    binding_host_id: "{{ vm.name }}"
    binding_vnic_type: "normal"
    binding_profile:
      workload_name: "{{ vm.name }}"
      nic_order: "{{ loop.index }}"
  register: neutron_ports
  loop: "{{ ovirt_vms }}"
  loop_control:
    loop_var: vm
