---
- name: Gather facts about oVirt VMs
  ovirt.ovirt.ovirt_vm_info:
    hostname: "{{ ovirt_hostname }}"
    username: "{{ ovirt_username }}"
    password: "{{ ovirt_password }}"
    ca_file: "{{ ovirt_ca_file }}"
  register: ovirt_vms

- name: Classify VMs into flavors
  set_fact:
    vm_flavors: "{{ vm_flavors | default([]) + [item | classify_vm(flavor_sizes)] }}"
  loop: "{{ ovirt_vms.ovirt_vms }}"
  vars:
    flavor_sizes: "{{ flavor_sizes }}"
    classify_vm: "{{ lookup('template', classify_vm_template) }}"

- name: Count VMs per flavor
  set_fact:
    vm_counts: "{{ vm_counts | default({}) | combine({item: vm_flavors | select('equalto', item) | list | length}) }}"
  loop: "{{ vm_flavors | unique }}"

- name: Debug VM counts per flavor
  debug:
    msg: "Flavor: {{ item }}, Count: {{ vm_counts[item] }}"
  loop: "{{ vm_flavors | unique }}"

- name: Create flavors in OpenStack
  openstack.cloud.flavor:
    name: "{{ item.key }}"
    state: present
    ram: "{{ item.value.memory }}"
    vcpus: "{{ item.value.cpu }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project_name }}"
      user_domain_name: "{{ openstack_user_domain_name }}"
      project_domain_name: "{{ openstack_project_domain_name }}"
  loop: "{{ flavor_sizes | dict2items }}"
