---
- name: Gather facts about oVirt networks
  ovirt.ovirt.ovirt_network_info:
    hostname: "{{ ovirt_hostname }}"
    username: "{{ ovirt_username }}"
    password: "{{ ovirt_password }}"
    ca_file: "{{ ovirt_ca_file }}"
  register: ovirt_networks

- name: Create networks in OpenStack
  openstack.cloud.network:
    state: present
    name: "{{ item.vlan_tag }}"
    shared: "{{ openstack_network_shared }}"
    provider_physical_network: "{{ item.name }}"
    provider_network_type: vlan
    provider_segmentation_id: "{{ item.vlan_tag }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project_name }}"
      user_domain_name: "{{ openstack_user_domain_name }}"
      project_domain_name: "{{ openstack_project_domain_name }}"
  loop: "{{ ovirt_networks.ovirt_networks | selectattr('usages', 'equalto', 'vm') | list }}"
  when: item.usages == "vm"

