- name: Create snapshot of VM disks
  ovirt.ovirt.ovirt_snapshot:
    hostname: "{{ ovirt_hostname }}"
    username: "{{ ovirt_username }}"
    password: "{{ ovirt_password }}"
    ca_file: "{{ ovirt_ca_file }}"
    vm_name: "{{ vm.name }}"
    description: "Exporting snapshot for {{ vm.name }}"
    wait: yes
  register: snapshot_result
  loop: "{{ ovirt_vms.ovirt_vms | selectattr('name', 'in', ovirt_target_vms) | list }}"
  loop_control:
    loop_var: vm

- name: Download snapshot disk image
  ovirt.ovirt.ovirt_snapshot:
    hostname: "{{ ovirt_hostname }}"
    username: "{{ ovirt_username }}"
    password: "{{ ovirt_password }}"
    ca_file: "{{ ovirt_ca_file }}"
    vm_name: "{{ vm.name }}"
    snapshot_id: "{{ snapshot_result.snapshot.id }}"
    download_image_path: "/tmp/{{ vm.name }}-{{ snapshot_result.snapshot.id }}.qcow2"
  loop: "{{ snapshot_result.results }}"
  loop_control:
    loop_var: snapshot_result

- name: Upload downloaded disk image to Glance
  openstack.cloud.image:
    state: present
    name: "{{ vm.name }}-{{ snapshot_result.snapshot.id }}"
    filename: "/tmp/{{ vm.name }}-{{ snapshot_result.snapshot.id }}.qcow2"
    container_format: bare
    disk_format: qcow2
    is_public: no
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project_name }}"
      user_domain_name: "{{ openstack_user_domain_name }}"
      project_domain_name: "{{ openstack_project_domain_name }}"
  register: glance_image
  loop: "{{ snapshot_result.results }}"
  loop_control:
    loop_var: snapshot_result

- name: Create Cinder volumes from Glance images
  openstack.cloud.volume:
    state: present
    display_name: "{{ vm.name }}-{{ snapshot_result.snapshot.id }}"
    size: "{{ (vm.memory / (2**30)) | round(0, 'ceil') | int }}"
    image: "{{ glance_image.image.id }}"
    metadata:
      workload_name: "{{ vm.name }}"
      disk_order: "{{ loop.index }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project_name }}"
      user_domain_name: "{{ openstack_user_domain_name }}"
      project_domain_name: "{{ openstack_project_domain_name }}"
  register: cinder_volumes
  loop: "{{ glance_image.results }}"
  loop_control:
    loop_var: glance_image

- name: Remove created snapshot
  ovirt.ovirt.ovirt_snapshot:
    hostname: "{{ ovirt_hostname }}"
    username: "{{ ovirt_username }}"
    password: "{{ ovirt_password }}"
    ca_file: "{{ ovirt_ca_file }}"
    vm_name: "{{ vm.name }}"
    snapshot_id: "{{ snapshot_result.snapshot.id }}"
    state: absent
    wait: yes
  when: ovirt_remove_snapshot | default(false) | bool
  loop: "{{ snapshot_result.results }}"
  loop_control:
    loop_var: snapshot_result

- name: Remove Glance image after copying to Cinder volume
  openstack.cloud.image:
    state: absent
    name: "{{ vm.name }}-{{ snapshot_result.snapshot.id }}"
    auth:
      auth_url: "{{ openstack_auth_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project_name }}"
      user_domain_name: "{{ openstack_user_domain_name }}"
      project_domain_name: "{{ openstack_project_domain_name }}"
  when: glance_remove_snapshot | default(false) | bool
  loop: "{{ glance_image.results }}"
  loop_control:
    loop_var: glance_image

